language: cpp
sudo: required
compiler:
    - clang
    - gcc
os:
    - linux
before_install:
    - sudo apt-get update  -qq
    - sudo apt-get install -qq libpthread-stubs0-dev libsqlite3-dev liblua50-dev zlib1g-dev
script:
    - mkdir build
    - cd build
    - cmake .. && make
