# Enable C++ support
sudo      : required
language  : cpp

# Compiler selection
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

before_install:
  - sudo apt-get update  -qq
  - sudo apt-get install -qq libsqlite3-dev liblua5.2-dev zlib1g-dev
#libpthread-stubs0-dev

# Build steps
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
