---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by enrico.
--- DateTime: 9/13/19 9:41 AM
---

mud = {}

mud.log = function(message)
    return MudFunction.log(message)
end

mud.random = function(min, max)
    return MudFunction.random(min, max)
end

mud.stop = function()
    return MudFunction.stop()
end

mud.load_item = function(character, vnumModel, vnumMaterial, qualityValue)
    return MudFunction.loadItem(character, vnumModel, vnumMaterial, qualityValue)
end

mud.find_path = function(character, room)
    return MudFunction.findPath(character, room)
end

mud.get_rooms_in_sight = function(character)
    return MudFunction.getRoomsInSight(character)
end

mud.get_characters_in_sight = function(character)
    return MudFunction.getCharactersInSight(character)
end

mud.get_items_in_sight = function(character)
    return MudFunction.getItemsInSight(character)
end